[build]
target = "index.html"
dist = "dist"
pattern_script = """\
    <script type="module">\
        // Just prevent the default import. We'll do this manually.
        // {base}{js}
    </script>\
"""
filehash = false